baseURL = "https://mariannakeen.netlify.com/"
languageCode = "en-us"
title = "Marianna Keen"
enableGitInfo = true
enableEmoji = true

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4
