baseURL = "https://mariannakeen.netlify.com/"
languageCode = "en-us"
title = "TESTSITE ZERO"
enableGitInfo = true
enableEmoji = true

[taxonomies]
tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4
