baseURL = "https://testsitezero.netlify.com/"
languageCode = "en-us"
title = "TESTSITE ZERO"
enableGitInfo = true
enableEmoji = true

[taxonomies]
tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "hrdark"
    tabWidth = 4
